BEGIN;

create table `commodity` (
    SKU VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    IMAGE JSON NULL,
    PRICE VARCHAR(50) NOT NULL
);
COMMIT;